### ISSUE TITLE
New "scripts" property to setup global pre/post scripts

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Parcel#10]
Packages each have their own pre/post install/uninstall script properties, as well as each provider - soon. This is to create a global one for running a pre-install script before all installations begins (etc.):

```yaml
---
scripts:
  pre:
    install:
    uninstall:
  post:
    install:
    uninstall:

packages:
- name: etc
```

This can just re-use the same `[ParcelScripts]` class like packages.
