### ISSUE TITLE
New "provider" property, to allow further custom configuration of providers

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Parcel#11]
To allow for further custom configuration of providers, there should be a new `providers:` block.

This should allow for custom `sources`, and custom global `args` that will be used for each package of that provider.

```yaml
providers:
  choco:
    sources:
    - name: '<source-name>'
      url: '<source-url>'
    args:
      install: '--noprogress'

  scoop:
    sources:
    - name: '<bucket-name>'
      url: '<bucket-url>'
```
