### ISSUE TITLE
Support for custom Arguments

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Parcel#2]
At the moment, you can't supply any custom optional arguments for a package/provider - such as `-MinimumVersion` for `Install-Module`.

This should be do via a new `args` property:

```yaml
---
packages:
- name: Pode
  provider: psgallery
  args: -MinimumVersion 1.0.1
```

**Comment by Badgerati** [comment]
New idea on this, if `args:` is a string, use that on install and uninstall. However, you can also supply specific install/uninstall:

This applies to install and uninstall:
```yaml
packages:
- name: Pode
  provider: psgallery
  args: -MinimumVersion 1.0.1
```

This uses different args for each:
```yaml
packages:
- name: Pode
  provider: psgallery
  args:
    install: -MinimumVersion 1.0.1
    uninstall: -SomeArgs
```
