### ISSUE TITLE
Support for custom Sources/Repository

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Parcel#3]
Currently the installs occur from the official sources, there should be support for custom sources (like on choco/psgallery, or for scoop and its buckets):

```yaml
---
packages:
- name: 7zip.install
  provider: choco
  source: http://some.custom.source.com
```
