### ISSUE TITLE
Support for latest versions

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Parcel#4]
At the moment, you need to always supply an actual version - even for latest versions, rather than just "latest".

Like with Fudge, when no version or latest is supplied, the actual latest version should be retrieved. This allows us to show what version is actually being installed, and to use when uninstalling.

```yaml
---
packages:
- name: 7zip
  provider: choco
  version: latest #< this should be possible
```
